event.max_chance_battle=70
player.increase_experience_after_battle=50
ability.base_attack_name=Базовая атака
#####################
#### Default monsters:
#####################
#### Goblin
monster.goblin.name=Goblin
monster.goblin.level=1
monster.goblin.max_health=50
monster.goblin.attack=10
#####################
#### Orc
monster.orc.name=Orc
monster.orc.level=2
monster.orc.max_health=300
monster.orc.attack=20